### ISSUE TITLE
Sphinx documentation missing

### ISSUE THREAD

**Issue by jacobjj** [ArthDh/ECE229#8]
Please provide instructions for getting Sphinx documentation.

**Comment by jboboyle** [comment]
Please see the updated readme and let us know the issue is not resolved

**Comment by jacobjj** [comment]
Getting Page not found errror - https://github.com/ArthDh/ECE229/blob/main/readme_images/Documentation.png.png?raw=true

**Comment by jboboyle** [comment]
Thanks. Should be resolved now

**Comment by ArthDh** [comment]
If you'd like to view the documentation without running the app it is available under:
`app/static/html/index.html`
